### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tomekb530** [Tenrys/gmod_discordrpc#1]
I've actually made the addon doing same thing on workshop, you will be mad if it will be on workshop ?

**Comment by tomekb530** [comment]
I am not using your code btw

**Comment by Tenrys** [comment]
Well I'll be upset because eventually I was planning to perfect it and add default states for various gamemodes, so it'll feel like you're stealing the spotlight from me, but if you did make your own version from scratch I guess it can't be helped. It's to be expected when things are open source I suppose

**Comment by tomekb530** [comment]
if you want i can delete my version, i found this a few hours after publishing mine on steam ;-;

**Comment by Tenrys** [comment]
I've ironed the most annoying bug out and am currently adding support for various gamemodes by default to post on the workshop, so I don't know. I'd like it if you did but you don't have to.

**Comment by tomekb530** [comment]
Okay so i'll delete my version :D
